### ISSUE TITLE
crash when looking at block (mod conflict)

### ISSUE THREAD

**Issue by TheRanker** [AlphaMode/TheOneProbe-Fabric#4]
so ive been looking into this issue which i have iwth my modpack. 
yes im aware its a mod conflict, as it works in vanilla and a lot of other modded situations.

but i need help to isolate the issue .. if anything in this crash / error that can help me resolve it that you can identify, please let me know. 

ive started breaking down the modpack. and trying to isolate it.  this is the error taht crashes once looking down at a block. 

[20:10:15] [Netty Local Client IO #0/ERROR]: Encountered exception while handling in channel with name "theoneprobe:packet_return_info"
io.netty.handler.codec.EncoderException: java.io.IOException: Root tag must be a named compound tag
	at net.minecraft.class_2540.method_30616(class_2540.java:452) ~[client-intermediary.jar:?]
	at net.minecraft.class_2540.method_10798(class_2540.java:432) ~[client-intermediary.jar:?]
	at net.minecraft.class_2540.method_10819(class_2540.java:485) ~[client-intermediary.jar:?]
	at mcjty.theoneprobe.network.NetworkTools.readItemStack(NetworkTools.java:14) ~[theoneprobe-fabric-1.18-5.1.1.jar:?]
	at mcjty.theoneprobe.apiimpl.elements.ElementItemStack.<init>(ElementItemStack.java:26) ~[theoneprobe-fabric-1.18-5.1.1.jar:?]
	at mcjty.theoneprobe.apiimpl.TheOneProbeImp$1.createElement(TheOneProbeImp.java:43) ~[theoneprobe-fabric-1.18-5.1.1.jar:?]
	at mcjty.theoneprobe.apiimpl.ProbeInfo.createElements(ProbeInfo.java:29) ~[theoneprobe-fabric-1.18-5.1.1.jar:?]
	at mcjty.theoneprobe.apiimpl.elements.AbstractElementPanel.<init>(AbstractElementPanel.java:63) ~[theoneprobe-fabric-1.18-5.1.1.jar:?]
	at mcjty.theoneprobe.apiimpl.elements.ElementHorizontal.<init>(ElementHorizontal.java:30) ~[theoneprobe-fabric-1.18-5.1.1.jar:?]
	at mcjty.theoneprobe.apiimpl.TheOneProbeImp$1.createElement(TheOneProbeImp.java:43) ~[theoneprobe-fabric-1.18-5.1.1.jar:?]
	at mcjty.theoneprobe.apiimpl.ProbeInfo.createElements(ProbeInfo.java:29) ~[theoneprobe-fabric-1.18-5.1.1.jar:?]
	at mcjty.theoneprobe.apiimpl.ProbeInfo.fromBytes(ProbeInfo.java:16) ~[theoneprobe-fabric-1.18-5.1.1.jar:?]
	at mcjty.theoneprobe.network.PacketReturnInfo.<init>(PacketReturnInfo.java:26) ~[theoneprobe-fabric-1.18-5.1.1.jar:?]
	at mcjty.theoneprobe.network.PacketHandler.lambda$registerMessagesClient$2(PacketHandler.java:40) ~[theoneprobe-fabric-1.18-5.1.1.jar:?]
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.receive(ClientPlayNetworkAddon.java:97) ~[fabric-networking-api-v1-1.0.21+d882b91560-8caffa82fdcf8532.jar:?]
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.receive(ClientPlayNetworkAddon.java:39) ~[fabric-networking-api-v1-1.0.21+d882b91560-8caffa82fdcf8532.jar:?]
	at net.fabricmc.fabric.impl.networking.AbstractChanneledNetworkAddon.handle(AbstractChanneledNetworkAddon.java:100) [fabric-networking-api-v1-1.0.21+d882b91560-8caffa82fdcf8532.jar:?]
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.handle(ClientPlayNetworkAddon.java:89) [fabric-networking-api-v1-1.0.21+d882b91560-8caffa82fdcf8532.jar:?]
	at net.minecraft.class_634.handler$ehp000$handleCustomPayload(class_634.java:2432) [client-intermediary.jar:?]
	at net.minecraft.class_634.method_11152(class_634.java) [client-intermediary.jar:?]
	at net.minecraft.class_2658.method_11457(class_2658.java:60) [client-intermediary.jar:?]
	at net.minecraft.class_2658.method_11054(class_2658.java:8) [client-intermediary.jar:?]
	at net.minecraft.class_2535.method_10759(class_2535.java:172) [client-intermediary.jar:?]
	at net.minecraft.class_2535.method_10770(class_2535.java:157) [client-intermediary.jar:?]
	at net.minecraft.class_2535.channelRead0(class_2535.java:55) [client-intermediary.jar:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:299) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.local.LocalChannel.finishPeerRead0(LocalChannel.java:445) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.local.LocalChannel.access$400(LocalChannel.java:50) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.local.LocalChannel$5.run(LocalChannel.java:403) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at java.lang.Thread.run(Thread.java:833) [?:?]

Caused by: java.io.IOException: Root tag must be a named compound tag
	at net.minecraft.class_2507.method_10625(class_2507.java:95) ~[client-intermediary.jar:?]
	at net.minecraft.class_2540.method_30616(class_2540.java:450) ~[client-intermediary.jar:?]
	... 40 more

[20:10:15] [Render thread/INFO]: Clearing audio channels
[20:10:15] [Render thread/INFO]: Stopping microphone thread
[20:10:15] [Server thread/INFO]: TheRanker lost connection: Internal Exception: java.nio.channels.ClosedChannelException
[20:10:15] [Server thread/INFO]: TheRanker left the game
[20:10:15] [Server thread/INFO]: Disconnecting client TheRanker
[20:10:15] [Render thread/INFO]: Disconnecting voicechat
[20:10:15] [Server thread/INFO]: Stopping singleplayer server as player logged out
[20:10:15] [Server thread/INFO]: Stopping server

**Comment by AlphaMode** [comment]
Do you have any mods messing with networking?

**Comment by TheRanker** [comment]
Krypton

**Comment by AlphaMode** [comment]
after some narrowing down if you have Numismatic Overhaul try removing it

**Comment by AlphaMode** [comment]
Fixed in latest commit
